In [145]:
#####Create Heatmaps for Weather Parameters#####
#Here in this program we are going to use the data we collected from "openweather maps" and created a csv named "citiesweather.csv"</br>
#as the datas for DF and then we are using Google's MapsJavaScript API to create the plot ,filesneeded:config.py which saves the key of googleAPI</br>
##to use the GoogleAPI to plot the graph.so we are not using any URL from Google 
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [146]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("citiesweather.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Tucurui,-3.7661,-49.6725,86.11,72,87,2.04,BR,2021-03-05 16:00:34
1,1,Pipri,19.8000,75.5333,78.80,34,0,2.30,IN,2021-03-05 16:00:35
2,2,Balsas,-7.5325,-46.0356,88.39,59,69,6.53,BR,2021-03-05 16:00:25
3,3,Rikitea,-23.1203,-134.9692,79.97,83,0,11.27,PF,2021-03-05 16:00:36
4,4,Porto Novo,6.4965,2.6036,89.60,70,20,17.27,BJ,2021-03-05 16:00:36

In [147]:
city_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City_ID     486 non-null    int64
 1   City        486 non-null    object
 2   Lat         486 non-null    float64
 3   Lng         486 non-null    float64
 4   Max Temp    486 non-null    float64
 5   Humidity    486 non-null    int64
 6   Cloudiness  486 non-null    int64
 7   Wind Speed  486 non-null    float64
 8   Country     483 non-null    object
 9   Date        486 non-null    object
dtypes: float64(4), int64(3), object(3)
memory usage: 38.1+ KB

In [148]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [149]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [150]:
# Get the maximum temperature.to avoid errors while interpreting max_temp into weights
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [151]:
##### Heatmap of temperature#####
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

# Assign the figure variable.#google API datas stored from the functions
fig = gmaps.figure()
# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4) 
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [152]:

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig

Figure(layout=FigureLayout(height='420px'))

In [153]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [154]:
#Create a Percent Cloudiness Heatmap
locations = city_data_df[["Lat", "Lng"]]
Cloudiness = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
cloudiness_layer = gmaps.heatmap_layer(locations, weights=Cloudiness, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(cloudiness_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [155]:
#Create a Wind Speed Heatmap

locations = city_data_df[["Lat", "Lng"]]
Wind_Speed = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
windspeed_layer = gmaps.heatmap_layer(locations, weights=Wind_Speed, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(windspeed_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [156]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
#max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 50

In [158]:
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the maximum temperature you would like for your trip? 60

In [159]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
8,8,New Norfolk,-42.7826,147.0587,51.80,66,90,11.50,AU,2021-03-05 16:00:38
10,10,Asau,46.4333,26.4000,57.20,35,0,8.05,RO,2021-03-05 16:00:39
27,27,Ushuaia,-54.8000,-68.3000,55.40,50,40,12.66,AR,2021-03-05 15:57:59
42,42,Ahipara,-35.1667,173.1667,59.18,82,8,5.64,NZ,2021-03-05 16:00:52
66,66,Lishui,28.4604,119.9103,52.79,87,100,3.74,CN,2021-03-05 16:01:03
69,69,Fuling,29.7022,107.3919,52.47,78,10,1.66,CN,2021-03-05 16:01:05
70,70,Batemans Bay,-35.7167,150.1833,54.00,85,35,5.64,AU,2021-03-05 16:00:07
73,73,Lagoa,39.0500,-27.9833,57.40,70,72,8.08,PT,2021-03-05 16:01:05
83,83,Kaitangata,-46.2817,169.8464,54.00,86,94,6.51,NZ,2021-03-05 16:01:08
90,90,Parsons,37.3403,-95.2611,52.00,58,90,12.66,US,2021-03-05 16:01:10

In [160]:
#To find any Null Values
preferred_cities_df.count()

City_ID       42
City          42
Lat           42
Lng           42
Max Temp      42
Humidity      42
Cloudiness    42
Wind Speed    42
Country       42
Date          42
dtype: int64

In [161]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
Country       0
Date          0
dtype: int64

In [19]:
preferred_cities_df.dropna()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
8,8,New Norfolk,-42.7826,147.0587,51.80,66,90,11.50,AU,2021-03-05 16:00:38
10,10,Asau,46.4333,26.4000,57.20,35,0,8.05,RO,2021-03-05 16:00:39
27,27,Ushuaia,-54.8000,-68.3000,55.40,50,40,12.66,AR,2021-03-05 15:57:59
42,42,Ahipara,-35.1667,173.1667,59.18,82,8,5.64,NZ,2021-03-05 16:00:52
66,66,Lishui,28.4604,119.9103,52.79,87,100,3.74,CN,2021-03-05 16:01:03
69,69,Fuling,29.7022,107.3919,52.47,78,10,1.66,CN,2021-03-05 16:01:05
70,70,Batemans Bay,-35.7167,150.1833,54.00,85,35,5.64,AU,2021-03-05 16:00:07
73,73,Lagoa,39.0500,-27.9833,57.40,70,72,8.08,PT,2021-03-05 16:01:05
83,83,Kaitangata,-46.2817,169.8464,54.00,86,94,6.51,NZ,2021-03-05 16:01:08
90,90,Parsons,37.3403,-95.2611,52.00,58,90,12.66,US,2021-03-05 16:01:10
95,95,Wajima,37.4000,136.9000,51.28,82,82,5.12,JP,2021-03-05 16:01:11
119,119,Hobart,-42.8794,147.3294,51.80,66,90,11.50,AU,2021-03-05 16:00:31
126,126,Mount Gambier,-37.8333,140.7667,55.40,67,90,11.50,AU,2021-03-05 16:01:17
144,144,Hasaki,35.7333,140.8333,51.80,93,90,3.44,JP,2021-03-05 16:01:22
151,151,Dunedin,-45.8742,170.5036,57.99,72,99,6.17,NZ,2021-03-05 15:59:39
152,152,Guilin,25.2819,110.2864,57.20,100,75,2.24,CN,2021-03-05 16:01:10
190,190,Challapata,-18.9000,-66.7667,53.67,54,100,2.01,BO,2021-03-05 16:01:32
211,211,Bereda,43.2686,-7.5406,55.99,72,51,8.99,ES,2021-03-05 16:01:38
232,232,Crotone,39.0851,17.1178,57.20,67,0,10.36,IT,2021-03-05 16:01:43
235,235,Enshi,30.3000,109.4833,51.10,83,78,0.16,CN,2021-03-05 16:01:44
249,249,Lasa,46.6166,10.7002,57.20,65,75,5.75,IT,2021-03-05 16:01:47
252,252,Dubbo,-32.2500,148.6167,59.00,72,0,8.05,AU,2021-03-05 16:01:48
257,257,Gazli,40.1333,63.4500,51.57,41,100,14.12,UZ,2021-03-05 16:01:49
265,265,Katsuura,35.1333,140.3000,53.60,100,75,4.99,JP,2021-03-05 16:01:50
271,271,Niimi,34.9833,133.4667,51.01,96,95,3.15,JP,2021-03-05 16:01:52
283,283,Dreznica,43.5289,17.2819,59.00,55,40,5.75,BA,2021-03-05 16:01:54
286,286,La Rioja,42.2500,-2.5000,59.00,58,40,6.91,ES,2021-03-05 16:01:54
295,295,Wenling,28.3669,121.3600,53.01,92,99,6.82,CN,2021-03-05 16:01:56
297,297,Nogales,31.3086,-110.9422,53.01,56,1,7.18,MX,2021-03-05 16:00:13
309,309,Half Moon Bay,37.4636,-122.4286,53.01,87,1,6.04,US,2021-03-05 16:02:00
330,330,Cabra,37.4725,-4.4421,55.99,79,100,2.46,ES,2021-03-05 16:02:05
332,332,Oga,46.4631,10.3470,52.00,74,75,12.66,IT,2021-03-05 16:02:05
333,333,Codrington,-38.2667,141.9667,53.22,76,83,10.09,AU,2021-03-05 16:02:06
356,356,Qianjiang,30.4151,112.8859,51.76,91,97,9.17,CN,2021-03-05 16:02:11
374,374,Kashi,39.4547,75.9797,50.00,32,75,11.18,CN,2021-03-05 16:02:16
380,380,Pecos,31.4229,-103.4932,57.20,28,1,17.27,US,2021-03-05 16:02:17
383,383,Fortuna,40.5982,-124.1573,54.00,77,100,8.01,US,2021-03-05 16:02:18
384,384,Hirado,33.3597,129.5531,57.00,66,100,5.99,JP,2021-03-05 16:02:19
453,453,Midland,31.9974,-102.0779,57.99,44,1,19.57,US,2021-03-05 16:02:33
469,469,Kushima,31.4583,131.2333,59.85,86,98,3.13,JP,2021-03-05 16:02:38
471,471,Albacete,38.8333,-2.0000,53.60,62,20,8.05,ES,2021-03-05 16:02:38
478,478,Murray Bridge,-35.1167,139.2667,54.00,94,19,6.62,AU,2021-03-05 16:02:40

In [162]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(15)

              City Country  Max Temp      Lat       Lng Hotel Name
8      New Norfolk      AU     51.80 -42.7826  147.0587
10            Asau      RO     57.20  46.4333   26.4000
27         Ushuaia      AR     55.40 -54.8000  -68.3000
42         Ahipara      NZ     59.18 -35.1667  173.1667
66          Lishui      CN     52.79  28.4604  119.9103
69          Fuling      CN     52.47  29.7022  107.3919
70    Batemans Bay      AU     54.00 -35.7167  150.1833
73           Lagoa      PT     57.40  39.0500  -27.9833
83      Kaitangata      NZ     54.00 -46.2817  169.8464
90         Parsons      US     52.00  37.3403  -95.2611
95          Wajima      JP     51.28  37.4000  136.9000
119         Hobart      AU     51.80 -42.8794  147.3294
126  Mount Gambier      AU     55.40 -37.8333  140.7667
144         Hasaki      JP     51.80  35.7333  140.8333
151        Dunedin      NZ     57.99 -45.8742  170.5036

In [163]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42 entries, 8 to 478
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        42 non-null     object
 1   Country     42 non-null     object
 2   Max Temp    42 non-null     float64
 3   Lat         42 non-null     float64
 4   Lng         42 non-null     float64
 5   Hotel Name  42 non-null     object
dtypes: float64(3), object(3)
memory usage: 2.3+ KB

In [164]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
         }

In [165]:
# Set the parameters to search for a hotel in New Norfolk.
params = {
    "radius": 5000,
    "types": "lodging",
   "key": g_key,
   "location": "-42.7826, 147.0587"}
# Use base URL to search for hotels in New Norfolk.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
 #Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'ATtYBwJnw7XuMqKzp-Q8OvJyw69Vs97plTPxWn_rhptES2t3OJ4iyCS06iDQZ5auWonQd8Ald15F5WPLw5kmmzY3CEvQYPXb6aQnhOJhYtkTXI8NGHiHzxbyytLaF4LaxU9zBLrKHS3LkDUyGmLTT5yxmNFy53jjgXlTKWkeW0vie7AVGMBNuGPVvS0pJk8fjdgfLuf6t39n5DYPeqcHFpyENH5ocTNnC5Hi6eIk_Pyrp6gNtD4KM1_2HsO6C5AoabP66BARrfHOAGIJKPD_LLm0neBu9T_nman-UTeHzHroy76-r5Fce5PXdMH0-M2YMCnte4sso94qXlYp2plnCdDUxeiGcnd304zoo8a0f7UME4ssBzeUkt6TqpC7QTdQEdIqP7ntfYviqxOeBZCjwVnZAv2vNYu6tmaq7NKWeihI7uhOG4L1C2irQiJj',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.782249, 'lng': 147.0469615},
    'viewport': {'northeast': {'lat': -42.7811168697085,
      'lng': 147.0483348302915},
     'southwest': {'lat': -42.7838148302915, 'lng': 147.0456368697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'The Shingles Riverside Cottages',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3744,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/100963385608150117917">The Shingles Riverside Cottages</a>'],
     'photo_reference': 'ATtYBwLvNcN-B6uSUj1dryyKK6uiiwQGEiRo4i7-nVF-fq6KOf4GHjpUa6qmtBbd-CXAoJbb_46I0kAoT7As4MjwafRC7wOO7fz_ktuuZB2MWriYTYQOOEW1f1ORHGywMd7Sn05FAErjv77RQUSBMEvrR8ea66JdxjTSlbk8PAr10GHTN2ZZ',
     'width': 5616}],
   'place_id': 'ChIJH9Cqy3lrbqoRDB-yx4bTYi4',
   'plus_code': {'compound_code': '629W+4Q New Norfolk TAS, Australia',
    'global_code': '4R99629W+4Q'},
   'rating': 4.7,
   'reference': 'ChIJH9Cqy3lrbqoRDB-yx4bTYi4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 37,
   'vicinity': '117 Glenora Road, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7776465, 'lng': 147.0648117},
    'viewport': {'northeast': {'lat': -42.7763389697085,
      'lng': 147.0661827802915},
     'southwest': {'lat': -42.7790369302915, 'lng': 147.0634848197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Old Colony Inn',
   'photos': [{'height': 3456,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115131320014679778076">Trish Davison</a>'],
     'photo_reference': 'ATtYBwLbn2HO2Sie0G69FQuLk3KTQdi01CtI_KJI4yiBnzekkkJif5zP-90EpVyR3_hVe02oILti3BUuzEqeF6zO0F7OGHwyM572X5QC40c0_kjLWMDecHpak1L-600ED_jQ5kqmBsOEocu8RcjsyQChb1NN6HfBO4CZx4M3Wpp-QxOUjY-b',
     'width': 4608}],
   'place_id': 'ChIJN8TUUWJrbqoRC3cqqtMACSc',
   'plus_code': {'compound_code': '63C7+WW New Norfolk TAS, Australia',
    'global_code': '4R9963C7+WW'},
   'rating': 4.2,
   'reference': 'ChIJN8TUUWJrbqoRC3cqqtMACSc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 16,
   'vicinity': '21 Montagu Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7721137, 'lng': 147.0649744},
    'viewport': {'northeast': {'lat': -42.7708249697085,
      'lng': 147.0662178302915},
     'southwest': {'lat': -42.7735229302915, 'lng': 147.0635198697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Explorers Lodge',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104439284775594206814">Explorers Lodge</a>'],
     'photo_reference': 'ATtYBwIy7fx3e4MAWgTtGpJTfFGLQye2YhbV0VHtANeKOKsf_TJm7IHu2GxoxyK5bwaRCRsrQN0bYHjT_9ZKZig7ISlUyq0gzayJHC48r6ubOHxeyaDgg43dEwXjeqNCcKt9rw6LI5M_av_lBTVUrxyToBPsn5meMcrBZwyIa2au0OI0ufzQ',
     'width': 3264}],
   'place_id': 'ChIJrRMUQWdrbqoRtsjAoGdD3NQ',
   'plus_code': {'compound_code': '63H7+5X New Norfolk TAS, Australia',
    'global_code': '4R9963H7+5X'},
   'rating': 4.5,
   'reference': 'ChIJrRMUQWdrbqoRtsjAoGdD3NQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 20,
   'vicinity': '105 Derwent Terrace, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.77937379999999, 'lng': 147.0578731},
    'viewport': {'northeast': {'lat': -42.77801296970851,
      'lng': 147.0592519302915},
     'southwest': {'lat': -42.7807109302915, 'lng': 147.0565539697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'The Woodbridge',
   'photos': [{'height': 756,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110147371820850774027">The Woodbridge</a>'],
     'photo_reference': 'ATtYBwI3VJBu8U17PFNVjAUiKhNy7Q-NeVHC2v8WpvDTFtJwTIy5-0zssBkJd9juT1bxaJTQ-PsmxJlOwVDD4kEEbYpc_JSi54Zt9wF_6oXJk-QBvU03LGRvjnlaX9dnUbVO4WFxImZuUT5UCK0fvsGKGEAYjLweBFJ7GbxVcWgJPz53Oxkv',
     'width': 1500}],
   'place_id': 'ChIJ59WmpnxrbqoR0RaaSpF0sSY',
   'plus_code': {'compound_code': '63C5+74 New Norfolk TAS, Australia',
    'global_code': '4R9963C5+74'},
   'rating': 4.8,
   'reference': 'ChIJ59WmpnxrbqoR0RaaSpF0sSY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 18,
   'vicinity': '6 Bridge Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.779464, 'lng': 147.062299},
    'viewport': {'northeast': {'lat': -42.7779907697085,
      'lng': 147.0636606802915},
     'southwest': {'lat': -42.78068873029149, 'lng': 147.0609627197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hillside Cottage',
   'photos': [{'height': 1876,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105149107450076998569">Hillside Cottage</a>'],
     'photo_reference': 'ATtYBwIqQc-FbuKboF-ZdZ6qClLowkxbknKIQ6UCV_VmEB8b9s8af-3HBAmo2EvM0UL5-mIBj36HCldbhyPMIXMMJtzo6ojVoWPhM4y50Vg1Ozf3IpGdIpDasGISg2Ap16oYapu5yDyUqh1CW-WluB1Wbwp4TwNGKnTe7OZhxYnA8v_77zFd',
     'width': 2048}],
   'place_id': 'ChIJWzjG0GJrbqoRxK5AkvRdEoM',
   'plus_code': {'compound_code': '63C6+6W New Norfolk TAS, Australia',
    'global_code': '4R9963C6+6W'},
   'rating': 5,
   'reference': 'ChIJWzjG0GJrbqoRxK5AkvRdEoM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '9 Hillside Crescent, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7799418, 'lng': 147.066727},
    'viewport': {'northeast': {'lat': -42.7784896197085,
      'lng': 147.0680146802915},
     'southwest': {'lat': -42.7811875802915, 'lng': 147.0653167197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Saints & Sinners B&B / Cafe',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 999,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106115724639215034448">Saints &amp; Sinners B&amp;B / Cafe</a>'],
     'photo_reference': 'ATtYBwKpvkZBFbjOLE1m4brVDkxxbbM27KeQoEVVy3WQo8J5ljPJbmmqlIGkH_H_GI90VfzS4S993exVjuMMjKDzq2hC0FBp_JZ2ZBx0XBuOCY9yAXb1EqZZ7V5Nq7K1W9OjchXbWGlEb6xXA9E16mCsDUXffaUqxz93GmgomZ9MQSXWbrwl',
     'width': 1499}],
   'place_id': 'ChIJ0R0jaZ1sbqoRzX3eKn4kqVE',
   'plus_code': {'compound_code': '63C8+2M New Norfolk TAS, Australia',
    'global_code': '4R9963C8+2M'},
   'rating': 4.8,
   'reference': 'ChIJ0R0jaZ1sbqoRzX3eKn4kqVE',
   'scope': 'GOOGLE',
   'types': ['cafe',
    'lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 6,
   'vicinity': '93 High Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7778918, 'lng': 147.0513797},
    'viewport': {'northeast': {'lat': -42.7764985697085,
      'lng': 147.0527222302915},
     'southwest': {'lat': -42.77919653029149, 'lng': 147.0500242697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Glen Derwent',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2269,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109407142586001125239">Glen Derwent</a>'],
     'photo_reference': 'ATtYBwJsUFDxfiNnEBBBqInJATtGGmtxAecPak3GDpMFkLTGcgrFLORheDiTGVlqxWJbuFLqUBPiXbpsYnvrdBLnT9V7k3qEFyI0BHbiUaPn0trW8FC4-gxuqzP8NYJcfi1dtSgHzUcfy5p2WnS1C98_cjvgK1iHkWtTOZhug9zFuXUSkJz6',
     'width': 4032}],
   'place_id': 'ChIJk0_17HprbqoRBuRWus9BJxk',
   'plus_code': {'compound_code': '63C2+RH New Norfolk TAS, Australia',
    'global_code': '4R9963C2+RH'},
   'rating': 4.7,
   'reference': 'ChIJk0_17HprbqoRBuRWus9BJxk',
   'scope': 'GOOGLE',
   'types': ['cafe', 'lodging', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 87,
   'vicinity': '88 Hamilton Road, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7506553, 'lng': 147.0612402},
    'viewport': {'northeast': {'lat': -42.7492285197085,
      'lng': 147.0622193802915},
     'southwest': {'lat': -42.7519264802915, 'lng': 147.0595214197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Stanton Bed and Breakfast',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104998437522096519193">Persia Shakari</a>'],
     'photo_reference': 'ATtYBwJHHR9p39AnSxURETwYK4x2IhIjX1x8rtH-E_lwUYUtpPhU8rUNrBGfy2AdoYGPGJyu7SKQyrB--Uht0hnSJgT0kqKB59kV0k6o7KuoUPl6DyDl0EIB2JznLoRuQflLsXhsdYFgRdw5fV-3hdCNe7LiayG8YlKsW5M3JsWDpiYuT7bg',
     'width': 4032}],
   'place_id': 'ChIJV52H3DRrbqoRjfuQpY1TPZs',
   'plus_code': {'compound_code': '63X6+PF Magra TAS, Australia',
    'global_code': '4R9963X6+PF'},
   'rating': 5,
   'reference': 'ChIJV52H3DRrbqoRjfuQpY1TPZs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 11,
   'vicinity': '504 Back River Road, Magra'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.77546, 'lng': 147.0406292},
    'viewport': {'northeast': {'lat': -42.7738626197085,
      'lng': 147.0420305802915},
     'southwest': {'lat': -42.77656058029149, 'lng': 147.0393326197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Oakdale B & B',
   'opening_hours': {'open_now': True},
   'place_id': 'ChIJaY4bAnNrbqoR8MqBOmhozPE',
   'plus_code': {'compound_code': '62FR+R7 New Norfolk TAS, Australia',
    'global_code': '4R9962FR+R7'},
   'rating': 3.5,
   'reference': 'ChIJaY4bAnNrbqoR8MqBOmhozPE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2,
   'vicinity': '10 Oakdale Road, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7776317, 'lng': 147.0684438},
    'viewport': {'northeast': {'lat': -42.7763561197085,
      'lng': 147.0698490802915},
     'southwest': {'lat': -42.77905408029149, 'lng': 147.0671511197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Junction Motel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3806,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105301313106211484988">Emma Rodda</a>'],
     'photo_reference': 'ATtYBwLyQdJINptyHcMUa7R15deN2nW6dCt5bOMOaKbQ0RMbIdmKAARQfFlisu1e3ws57tzTLuuImj2kRw3mREiKkJCbWwlF5VM8uAGzyexSOsG6b0YbOExx_nyNCuW3QPu1JfO9pjX5qumT0x-p3SzyofOaX1CxrNYYur3aQZIkrQHhaHV5',
     'width': 16382}],
   'place_id': 'ChIJw8_N_p1sbqoRbKoDTwDam5U',
   'plus_code': {'compound_code': '63C9+W9 New Norfolk TAS, Australia',
    'global_code': '4R9963C9+W9'},
   'rating': 4.2,
   'reference': 'ChIJw8_N_p1sbqoRbKoDTwDam5U',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 119,
   'vicinity': 'Cnr Lyell Highway &, 50 Pioneer Avenue, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.775558, 'lng': 147.0766756},
    'viewport': {'northeast': {'lat': -42.7742265697085,
      'lng': 147.0779775802915},
     'southwest': {'lat': -42.7769245302915, 'lng': 147.0752796197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Tynwald Willow Bend Estate',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1200,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102533375597913523214">Tynwald Willow Bend Estate</a>'],
     'photo_reference': 'ATtYBwL3_kcMEnYjazJqr0G9NgYI7l2khwytkjNX-AHvH1k3PxdK4XKjslwOwRLeYQQ5MwLOTCDLBO7-D6MD04p-lu2w2lWobQEc030FmhiRPURiuKJXfA9g-3BWt4_ll3F8ODMk5ogsUn0t8cH043mrqiYd2WEzBbbAlkUJmbLl19I0k-Bt',
     'width': 1600}],
   'place_id': 'ChIJpwYz4J5sbqoRYY8EvFU1UsQ',
   'plus_code': {'compound_code': '63FG+QM New Norfolk TAS, Australia',
    'global_code': '4R9963FG+QM'},
   'price_level': 3,
   'rating': 4.6,
   'reference': 'ChIJpwYz4J5sbqoRYY8EvFU1UsQ',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 52,
   'vicinity': '1 Tynwald Road, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.78038799999999, 'lng': 147.0652013},
    'viewport': {'northeast': {'lat': -42.77895706970849,
      'lng': 147.0664973302915},
     'southwest': {'lat': -42.78165503029149, 'lng': 147.0637993697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'New Norfolk Hotel Tote Betting Outlet',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 3036,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103021389699817080342">Liam McLennan</a>'],
     'photo_reference': 'ATtYBwJQUMdyzUmMc3UTwy2ESk4jZyxzNHPKD4XqN5fS-mfKSkeXF5RRy8eq4KQDhNGMfeqC1Y5iYinTXq8LaqYP2DomIK8AkehV8whZ-PkcKjOwSvXfbu3i96A3ijWjJwJTnJReSPJwvoDXdFmuxgR1F7lNotKM4C8L53SKNTI2qn9KXhTt',
     'width': 4048}],
   'place_id': 'ChIJaQX5WJ1sbqoRf8BUVmJQ2Ac',
   'plus_code': {'compound_code': '6398+R3 New Norfolk TAS, Australia',
    'global_code': '4R996398+R3'},
   'price_level': 2,
   'rating': 3.9,
   'reference': 'ChIJaQX5WJ1sbqoRf8BUVmJQ2Ac',
   'scope': 'GOOGLE',
   'types': ['lodging', 'bar', 'point_of_interest', 'establishment'],
   'user_ratings_total': 117,
   'vicinity': '79 High Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7788153, 'lng': 147.0614477},
    'viewport': {'northeast': {'lat': -42.7775284697085,
      'lng': 147.0628353302915},
     'southwest': {'lat': -42.7802264302915, 'lng': 147.0601373697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Bush Inn',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102828102139522334513">Old Timers Crafts</a>'],
     'photo_reference': 'ATtYBwIgcstohgBYaG3FVKm7Gotj8d6htqhYCluZcfEry4s7U2rzuLnLZH5D-MxkeNWalrFtH6mRH4ddn0HN_V-pGu4LodP3xRcg52jSfZbmqek2S7kcDXKxRsyhpzJxcKrZdvdjYjPQ242Gk0FEY_C1eU7joXOHe2jumPVKmCJkEnGK8830',
     'width': 4032}],
   'place_id': 'ChIJfySUPmNrbqoRaRTDr4iLA5s',
   'plus_code': {'compound_code': '63C6+FH New Norfolk TAS, Australia',
    'global_code': '4R9963C6+FH'},
   'rating': 4.1,
   'reference': 'ChIJfySUPmNrbqoRaRTDr4iLA5s',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 128,
   'vicinity': '49-51 Montagu Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7832598, 'lng': 147.0623758},
    'viewport': {'northeast': {'lat': -42.7818067697085,
      'lng': 147.0636582302915},
     'southwest': {'lat': -42.7845047302915, 'lng': 147.0609602697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Willow Court Motel',
   'photos': [{'height': 1536,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111076445360595725756">Anders Biro</a>'],
     'photo_reference': 'ATtYBwJKxXaNq4IS3epJ7lNYnM67NTPfQZ4_8w_UraNXsZ0Ms9kFNxSvSMYxwZAdBfENTwiR4Y1rsWPGJAAhsmk6NCkuhqOVnY8tU6bA7kl3ewMyiWqpOeFdZsSSfWss8o4fYrJJX2g_KaRL3psD5QDfOXlXofTTc66hXMdi9MCqmClMxc2A',
     'width': 2048}],
   'place_id': 'ChIJz-QUcoJsbqoRdTDV-488a7s',
   'plus_code': {'compound_code': '6386+MX New Norfolk TAS, Australia',
    'global_code': '4R996386+MX'},
   'rating': 3.6,
   'reference': 'ChIJz-QUcoJsbqoRdTDV-488a7s',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 22,
   'vicinity': '15 George Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7810678, 'lng': 147.0603157},
    'viewport': {'northeast': {'lat': -42.7798037697085,
      'lng': 147.0617356802915},
     'southwest': {'lat': -42.7825017302915, 'lng': 147.0590377197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': "Deb's B&B",
   'place_id': 'ChIJvaYLHH1rbqoRrdevW0_6AA8',
   'plus_code': {'compound_code': '6396+H4 New Norfolk TAS, Australia',
    'global_code': '4R996396+H4'},
   'rating': 5,
   'reference': 'ChIJvaYLHH1rbqoRrdevW0_6AA8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '15 Circle Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7831633, 'lng': 147.0625396},
    'viewport': {'northeast': {'lat': -42.7817266697085,
      'lng': 147.0638325302915},
     'southwest': {'lat': -42.7844246302915, 'lng': 147.0611345697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': "Jo Jo's Inn",
   'place_id': 'ChIJl4GVboJsbqoR3zBq6q9ZY7s',
   'plus_code': {'compound_code': '6387+P2 New Norfolk TAS, Australia',
    'global_code': '4R996387+P2'},
   'reference': 'ChIJl4GVboJsbqoR3zBq6q9ZY7s',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '43 George Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7794196, 'lng': 147.0625835},
    'viewport': {'northeast': {'lat': -42.7780241697085,
      'lng': 147.0640760802915},
     'southwest': {'lat': -42.7807221302915, 'lng': 147.0613781197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': "The King's Own Inn",
   'photos': [{'height': 2976,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108344407883960969788">The King&#39;s Own Inn</a>'],
     'photo_reference': 'ATtYBwJwiZ02oqCW0f14Ai-vU0g9OlccYzVSF0ExQx7E6FuZQFWfzsPDHSOF4u-EuCdHV_10G0eQ4Bl2xavr6lgidM1BBapltdwDoHZOnwEiXche_mRjtd5K-5LVFPYP60ICeT9hmbzRwCol4IPPOpaLzWwmT8PKrjt7qBT7-7sMWGlQs74D',
     'width': 3968}],
   'place_id': 'ChIJFcqI2mJrbqoRz7WyiOXM5bo',
   'plus_code': {'compound_code': '63C7+62 New Norfolk TAS, Australia',
    'global_code': '4R9963C7+62'},
   'rating': 5,
   'reference': 'ChIJFcqI2mJrbqoRz7WyiOXM5bo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4,
   'vicinity': '1 Hill Street, New Norfolk'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -42.7801093, 'lng': 147.0660343},
    'viewport': {'northeast': {'lat': -42.7786798697085,
      'lng': 147.0673354802915},
     'southwest': {'lat': -42.7813778302915, 'lng': 147.0646375197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Star & Garter Hotel and Bottle Shop',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 675,

In [166]:
hotels["results"][0]["name"]

'The Shingles Riverside Cottages'

In [167]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
#hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
#hotel_df["Hotel Name"] = ""
#hotel_df.head(10)



# Iterate through the DataFrame.
##for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    #lat = row["Lat"]
    #lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    #params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    #base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    #hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    #hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

In [168]:
# Iterate through the DataFrame.
#for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    #lat = row["Lat"]
    #lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    #params["location"] = f"({lat},{lng})"
    #print(params["location"])
    # Use the search term: "lodging" and our latitude and longitude.
    #base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    #hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    #hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']

In [200]:
# Iterate through the DataFrame.
#hotels = []
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    #print(params)
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    #len.(hotels['results'])
    #print(hotels)
    #hotels['results'][0]['name']
     #hotels["results"]["name"]
    # Grab the first hotel from the results and store the name.
    hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    except(IndexError):
         print("Hotel not found... skipping.")

IndexError: list index out of range

In [198]:
    print(hotels['results'][1]['name'])

IndexError: list index out of range